In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics
import scipy.stats as sps
from scipy.optimize import curve_fit
from numpy import exp



In [2]:
from google.colab import files
files.upload()

Saving report.csv to report.csv


{'report.csv': b'"MIP","STDIP","EKIP","SIP","MC","STDC","EKC","SC","TARGET"\n"97.234375","46.53635749",".558616451",".384429415","2.010033445","13.63437642","10.02234589","132.1256231","0"\n"42.578125","46.63833746","2.841558376","7.832819342","12.97157191","38.49884932","3.799727502","14.99083404","1"\n"97.171875","45.65617246",".721308334",".482644292","1.557692308","12.59077472","11.43467599","169.9231026","0"\n"42.0234375","33.02708757","3.6688856","19.64800538","87.90468227","86.47995077",".259049282","-1.504341473","1"\n"46.171875","36.15831279","3.294612925","13.59033242","14.00501672","43.68747295","3.424030632","11.5640852","1"\n"97.140625","47.77089438",".625218075",".740796144","4.193143813","26.46526062","6.927045631","49.62852693","0"\n"44.8671875","45.69333429","2.888739412","8.810672554","176.1195652","59.73772038","-1.785376578","2.940913427","1"\n"97.0625","47.27409273",".278467144",".435716882",".553511706","9.586325582","20.63675832","475.9621349","0"\n"97.0859375","

In [3]:
DATA = pd.read_csv("report.csv")
DATA

MIP      STDIP      EKIP  ...        EKC          SC  TARGET
0    97.234375  46.536357  0.558616  ...  10.022346  132.125623       0
1    42.578125  46.638337  2.841558  ...   3.799728   14.990834       1
2    97.171875  45.656172  0.721308  ...  11.434676  169.923103       0
3    42.023438  33.027088  3.668886  ...   0.259049   -1.504341       1
4    46.171875  36.158313  3.294613  ...   3.424031   11.564085       1
..         ...        ...       ...  ...        ...         ...     ...
197  47.031250  36.980979  3.744839  ...   0.973483   -0.141037       1
198  97.148438  37.160145  0.457632  ...   9.645039  104.454324       0
199  97.101562  46.205864  0.486238  ...  25.031765  682.519179       0
200  44.796875  44.724043  3.508989  ...   1.231090    0.754103       1
201  97.242188  41.991767  0.390350  ...   6.539063   44.921089       0

[202 rows x 9 columns]

In [4]:
DATA["MIP"].mean()

70.79517326732673

In [5]:
p = ['MIP',	'STDIP', 'EKIP', 'SIP', 'MC', 'STDC', 'EKC', 'SC']
r = ['MIPnorm',	'STDIPnorm', 'EKIPnorm', 'SIPnorm', 'MCnorm', 'STDCnorm', 'EKCnorm', 'SCnorm']
for j in range(0, len(p)):
    z = []
    xmax = DATA[p[j]].max()
    xmin = DATA[p[j]].min()
    for i in range(0,len(DATA[p[j]])):
        x = DATA[p[j]][i]
        z.append((x-xmin)/(xmax-xmin))
    DATA[r[j]]=z
print(DATA.MIPnorm.mean())
DATA.head(7)

0.5206502783086412


MIP      STDIP      EKIP  ...  STDCnorm   EKCnorm    SCnorm
0  97.234375  46.536357  0.558616  ...  0.050428  0.440305  0.195878
1  42.578125  46.638337  2.841558  ...  0.300425  0.208266  0.024745
2  97.171875  45.656172  0.721308  ...  0.039935  0.492970  0.251100
3  42.023438  33.027088  3.668886  ...  0.782845  0.076236  0.000645
4  46.171875  36.158313  3.294613  ...  0.352593  0.194257  0.019738
5  97.140625  47.770894  0.625218  ...  0.179434  0.324883  0.075350
6  44.867188  45.693334  2.888739  ...  0.513968  0.000000  0.007140

[7 rows x 17 columns]

In [6]:
X = pd.DataFrame(DATA[r])

In [7]:
y = pd.DataFrame(DATA['TARGET'])

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
reg = LogisticRegression(random_state=2019, solver='lbfgs').fit(X, y.values.ravel())

In [11]:
reg.predict_proba([[0.539, 0.162, 0.188, 0.653, 0.796, 0.233, 0.397, 0.065]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[0.4218309, 0.5781691]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, p=2)
neigh.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [15]:
NewObject = [0.539, 0.162, 0.188, 0.653, 0.796, 0.233, 0.397, 0.065]
neigh.predict([NewObject])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

In [16]:
neigh.kneighbors([NewObject])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


(array([[0.89395099, 0.91711915, 0.92737999, 0.94232422, 0.94812764]]),
 array([[37, 71, 68,  6, 93]]))